# Numpy for Ml

# Creating array

### an expression that sets A to be a 2 \times 3 2×3 numpy array (2 rows by 3 columns), containing any values you wish.

In [1]:
import numpy as np
A = np.array([[1,2,3], [4,5,6]])

# TRANSPOSING ARRAY

In [2]:
def tp(A):
    return np.transpose(A)

## Let A be 4×2 numpy array, B be a 4×3 array, and C be a 4×1 array. For each of the following expressions, indicate the shape of the result as a tuple of integers (recall python tuples use parentheses, not square brackets, which are for lists, and a tuple of a single object x is written as (x,) with a comma) or "none" (as a Python string with quotes) if it is illegal.

In [3]:
A=np.array([[1,2],[4,5],[6,7],[8,9]])
B=np.array([[1,2,3],[4,5,6],[7,8,9],[8,5,6]])
C=np.array([[1],[2],[4],[5]])
            

# LETS SEE THE SOME BASIC CONCEPT 

In [4]:
C*C

array([[ 1],
       [ 4],
       [16],
       [25]])

# Explanation:

The * operator in numpy corresponds to element-wise multiplication, so each element i,j of the product is equal to the product of C[i,j] and C[i,j]. Thus, the product should have the same shape as both of the original arrays, which is (4,1).

In [6]:
np.dot(C,C)  #!ERROR WILL COME

ValueError: shapes (4,1) and (4,1) not aligned: 1 (dim 1) != 4 (dim 0)

# Explanation:

Since C is a 2-D numpy array, the dot product is equivalent to matrix multiplication. However, matrix multiplication requires that the inner dimensions of the two arrays are equal

In [8]:
np.dot(np.transpose(C),C) #SHAPE IS (1,1)

array([[46]])

# As in the previous problem, since C and np.transpose(C) are 2-D numpy arrays, the dot product is equivalent to matrix multiplication

In [10]:
np.dot(A,B)#ERROR BECAUSE DIMESION NOT MATCHING

ValueError: shapes (4,2) and (4,3) not aligned: 2 (dim 1) != 4 (dim 0)

In [11]:
np.dot(A.T,B) #see the shape its (2,3),TRY TO FIND WHY?

array([[123, 110, 129],
       [143, 130, 153]])

In [15]:
D=np.array([1,2,3])


# Explanation:

Using one set of square brackets creates a 1-dimensional array, whose dimension is 3

In [16]:
A[:,1]

array([2, 5, 7, 9])

# Explanation:

The colon signifies to create a splice using every row of AA and the 1 indexes for the second column.

In [17]:
A[:,1:2]

array([[2],
       [5],
       [7],
       [9]])

# Explanation:

The colon signifies to create a splice using every row of A and the 1:2 is a splice for the second column.

# NOW LETS COME TO LEVEL 2 AND CREATE VECTORS

# a procedure that takes a list of numbers and returns a 2D numpy array representing a row vector containing those numbers.

In [18]:
def rv(value_list):
    return np.array([value_list])

# a procedure that takes a list of numbers and returns a 2D numpy array representing a column vector containing those numbers

In [19]:
def cv(value_list):
    return np.transpose(rv(value_list))

# FINDING LENGTH

# a procedure that takes a column vector and returns the vector's Euclidean length (or equivalently, its magnitude) as a scalar

In [20]:
def length(col_v):
   return np.sum(col_v*col_v)**0.5 

# Square each item of the original vector (this can be done with element-wise multiplication, col_v*col_v, or the built-in square function, np.square(col_v))
Sum up all the elements in the new vector (this can be done with np.sum())
Take the square root of the previous sum.

# Normalize

# a procedure that takes a column vector and returns a unit vector in the same direction.

In [21]:
def normalize (col_v):
    return col_v/length(col_v)

# NOW LETS RREPRESENT DATA

Alice has collected weight and height data of 3 people and has written it down below:
Weight, height
150, 5.8
130, 5.5
120, 5.3

She wants to put this into a numpy array such that each row represents one individual's height and weight in the order listed. Write code to set data equal to the appropriate numpy array:

In [22]:
data=np.array([[150,5.8],[130,5.5],[120,5.3]])

# TRANSFORM DATA BY MATRIX MULTIPLICATION

In [23]:
def transform(data):
    return (np.dot(data,np.array([[1],[1]])))

Explanation:

Here d is a 3x2 matrix. We can multiply d by a 2x1 column vector of 1s to sum each row of d. This then gives us a 3x1 column vector representing sums of each person's height and weight.